### ISSUE TITLE
TypeError: store() got an unexpected keyword argument 'safe' from markdown.htmlStash.store(code, safe=False)

### ISSUE THREAD

**Issue by mkj28** [errbotio/errbot#1255]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 5.2.0
* OS version: python:3.6-alpine3.8 
* Python version: 3.6.6
* Using a virtual environment: no

### Issue description

`!plugin config Webserver` not rendered back to Slack. Seeing this in logs instead:
```
!plugin config Webserver
{'HOST': '0.0.0.0',
 'PORT': 3141,
 'SSL': {'certificate': '',
         'enabled': False,
         'host': '0.0.0.0',
         'key': '',
         'port': 3142}}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/errbot/backends/slack.py", line 654, in send_message
    body = self.md.convert(msg.body)
  File "/usr/local/lib/python3.6/site-packages/markdown/core.py", line 265, in convert
    self.lines = prep.run(self.lines)
  File "/usr/local/lib/python3.6/site-packages/errbot/rendering/ansiext.py", line 509, in run
    placeholder = self.markdown.htmlStash.store(code, safe=False)
TypeError: store() got an unexpected keyword argument 'safe'
```

### Steps to reproduce

Enable Slack backend, type `!plugin config Webserver`

### Additional info

None

**Comment by GenPage** [comment]
Looks like an update of the markdown lib has deprecated `safe`. 

https://python-markdown.github.io/change_log/release-3.0/#safe_mode-and-html_replacement_text-keywords-deprecated

Will get a PR to get this fixed.

**Comment by GenPage** [comment]
Immediate fix will most likely require a bugfix to all release to pin the markdown package version - 
https://github.com/errbotio/errbot/blob/master/setup.py#L40

New releases we can attempting our own whitelisting

**Comment by frozenfoxx** [comment]
I'm still getting this error which is preventing me from using webhooks.

**Comment by frozenfoxx** [comment]
Super quick workaround for anyone else running into this that's using Docker, have your Dockerfile install an older version of Markdown which will fix it until Errbot's code is fixed.

_Dockerfile_:
```
[...]
RUN pip3 install -U \
    'markdown<3.0' \
    'errbot' \
    'errbot[slack]' \
    'slackclient'
[...]
```

**Comment by mkj28** [comment]
^^^ not 100% sure if related, but getting this if trying markdown<3.0:
`Could not find a version that matches pygments-markdown-lexer>=0.1.0.dev39`

(could be also pipenv bug...)

**Comment by zaughon** [comment]
It's working with `Markdown==2.6.11` for me, so installing that specific version could work as a workaround for now.
(... in case anyone come across this at some point)

**Comment by sijis** [comment]
This issue is resolved by pinning the markdown version. It should be included in any 6.x release.

We have created an issue regarding supporting a newer version of markdown.

**Comment by mkj28** [comment]
Still seeing same with 6.1.1:
` # pipenv install errbot` fails with:
```
ERROR: ERROR: Could not find a version that matches pygments-markdown-lexer>=0.1.0.dev39
```


pipenv graph:
![2019-09-10_1008](https://user-images.githubusercontent.com/2279299/64634796-eddf8900-d3b2-11e9-9a8e-16723612f3f3.png)

**Comment by mkj28** [comment]
cc @sijis ^^
