### PR TITLE
Fix #932: Update documentation and type hinting to avoid confusion

### LINKED ISSUE #932: Issue with uploading file using Slack client
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 4.3.4
* OS version: macOS 10.12.1
* Python version: 3.5.0
* Using a virtual environment: yes

### Issue description

Error when posting a file attachment to slack:

Error: Slack API call to files.upload failed: no_file_data

### Steps to reproduce

Submit a BytesIO file to the stream

```python
self.send_stream_request(
                msg.frm,
                BytesIO(r.content),
                name=filename,
            )
```

### Additional info

It looks like the issue may be within the plugin. I wanted to verify before submitting a pull request

Line: 573 in slack.py
```python
            resp = self.api_call('files.upload', data={
                'channels': stream.identifier.channelid,
                'filename': stream.name,
                'file': stream
                })
```

I believe the issue is with `'file': stream` it should be `'file': stream.raw`.

### PR DESCRIPTION
**Pull request by andrewthetechie**
For https://github.com/errbotio/errbot/issues/932, documenting these functions and type hinting them can help prevent future confusion. It also allows folks to run a static type checker on their plugins to catch these errors in a CI workflow.

I copied the typing from botplugin.py - BotPlugin.send_stream_request and base.py.Stream

### CODE REVIEW

**Comment by andrewthetechie** [comment]
Tests are failing due to #1249

**Comment by andrewthetechie** [comment]
@sijis I copied the type hinting directly from the parent classes. 

Here's the results of a mypy run on that file. There are problems, but non related to my change:
```
mypy /errbot/backends/slack.py
errbot/backends/slack.py:148: error: Incompatible types in assignment (expression has type "Callable[[Any], Any]", base class "Person" defined the type as "str")
errbot/backends/slack.py:149: error: Incompatible types in assignment (expression has type "Callable[[Any], Any]", base class "Person" defined the type as "str")
errbot/backends/slack.py:228: error: Incompatible types in assignment (expression has type "Callable[[Any], Any]", base class "Person" defined the type as "str")
errbot/backends/slack.py:686: error: "Identifier" has no attribute "channelid"
errbot/backends/slack.py:695: error: "Identifier" has no attribute "channelname"
errbot/backends/slack.py:716: error: "Identifier" has no attribute "channelname"
errbot/backends/slack.py:890: error: "Identifier" has no attribute "userid"
errbot/backends/slack.py:931: error: "Identifier" has no attribute "id"
errbot/backends/slack.py:933: error: "Identifier" has no attribute "channelid"
```
