### ISSUE TITLE
CLI: listing all available backends is broken in 6.0.0

### ISSUE THREAD

**Issue by selurvedu** [errbotio/errbot#1312]
### I am...

* [x] Reporting a bug

### I am running...

* Errbot version: 6.0.0a0 and 6.0.0
* OS version: Linux 4.20.7-1-default GNU/Linux
* Python version: 3.7.2
* Using a virtual environment: yes

### Issue description

The `-l` / `--list` option is broken in versions 6.0.0a0 and 6.0.0. It works correctly in version 5.2.0.

### Steps to reproduce

```shell
$ uname -o -r -s
Linux 4.20.7-1-default GNU/Linux
$ python3 -V
Python 3.7.2
$ mkdir -p /tmp/errbot
$ cd /tmp/errbot
$ python3 -m venv env
$ . env/bin/activate
(env) $ pip install -q errbot==6.0.0
(env) $ errbot -v
Errbot version 6.0.0
(env) $ errbot -i
Your Errbot directory has been correctly initialized !
Just do "errbot" and it should start in text/development mode.
(env) $ errbot -l
Traceback (most recent call last):
  File "/tmp/errbot/env/bin/errbot", line 11, in <module>
    sys.exit(main())
  File "/tmp/errbot/env/lib64/python3.7/site-packages/errbot/cli.py", line 201, in main
    from errbot.bootstrap import enumerate_backends
ImportError: cannot import name 'enumerate_backends' from 'errbot.bootstrap' (/tmp/errbot/env/lib64/python3.7/site-packages/errbot/bootstrap.py)
(env) $ pip install -q 'errbot<6.0.0'
(env) $ errbot -v
Errbot version 5.2.0
(env) $ errbot -l                                                                                                                     
Available backends:
                Graphic
                Hipchat
                IRC
                Null
                Slack
                Telegram
                Test
                Text
                XMPP
(env) $
```

**Comment by sijis** [comment]
@selurvedu I put in a PR with a likely fix. Would you want to try and validate that it fixes the issue?

**Comment by selurvedu** [comment]
@sijis Thanks, it works.
