### ISSUE TITLE
DIVERT_TO_PRIVATE is broken on HipChat

### ISSUE THREAD

**Issue by zoni** [errbotio/errbot#661]
```
12:53:21 ERROR    errbot.errBot             An error happened while processing a message ("!about"): Traceback (most recent call last):
  File "/home/zoni/Workspace/Projects/err/errbot/errBot.py", line 451, in _execute_and_send
    self.send_simple_reply(mess, self.process_template(template_name, reply), private)
  File "/home/zoni/Workspace/Projects/err/errbot/errBot.py", line 207, in send_simple_reply
    self.split_and_send_message(self.build_reply(mess, text, private))
  File "/home/zoni/Workspace/Projects/err/errbot/backends/xmpp.py", line 591, in build_reply
    elif mess.to.person == self.bot_config.BOT_IDENTITY['username']:
AttributeError: 'HipChatRoom' object has no attribute 'person'
"
Traceback (most recent call last):
  File "/home/zoni/Workspace/Projects/err/errbot/errBot.py", line 451, in _execute_and_send
    self.send_simple_reply(mess, self.process_template(template_name, reply), private)
  File "/home/zoni/Workspace/Projects/err/errbot/errBot.py", line 207, in send_simple_reply
    self.split_and_send_message(self.build_reply(mess, text, private))
  File "/home/zoni/Workspace/Projects/err/errbot/backends/xmpp.py", line 591, in build_reply
    elif mess.to.person == self.bot_config.BOT_IDENTITY['username']:
AttributeError: 'HipChatRoom' object has no attribute 'person'
12:53:21 DEBUG    errbot.backends.xmpp      build reply ...
```

This is a regression caused by #637 / #631
